from = "Shengyu Zhang <i@example.com>"
to = "Love Letter <loveletter@example.com>"
from_meimei_if_true_and_gege_if_false = false
created_at = "2025-04-03T13:07:14Z"
updated_at = "2025-04-03T13:07:14Z"
date = "2025-04-03"
title = "测试数据"
content = "张同学 我们这个 I 人交朋友的项目还有效咩 -- Best regards,Shengyu Zhang https://example.com "
