from = "Shengyu Zhang <gege@example.com>"
to = "Love Letter <loveletter@example.com>"
from_meimei_if_true_and_gege_if_false = false
created_at = "2025-04-03T13:07:14Z"
updated_at = "2025-04-03T13:07:14Z"
date = "2025-04-03"
title = "测试数据"
content = """
<div>张同学 我们这个 I 人交朋友的项目还有效咩</div><div> </div><div>-- </div><div>Best regards,</div><div>Shengyu Zhang</div><div> </div><div>https://example.com</div><div> </div>
"""
